export const GET_TODAY_FORECAST = 'GET_TODAY_FORECAST';
export const GET_NEXT_DAY_FORECAST = 'GET_NEXT_DAY_FORECAST';
export const GET_WEEK_FORECAST = 'GET_WEEK_FORECAST';
export const GET_MONTH_FORECAST = 'GET_MONTH_FORECAST';

export const LOAD_FORECAST_LIST_PENDING = 'pms/LOAD_FORECAST_LIST_PENDING';
export const LOAD_FORECAST_LIST_SUCCESS = 'pms/LOAD_FORECAST_LIST_SUCCESS';
export const LOAD_FORECAST_LIST_FAILURE = 'pms/LOAD_FORECAST_LIST_FAILURE';
